# Configuración de Plugin!
# Solo Tocar si Sabes lo que estás Haciendo
# Modificar algo de Aquí Puede Romper como Funciona el Juego
# Si no Sabes lo que estás haciendo, no toques nada [- Pbt]

# ------------------------------------------
#    Plugin - Configuración
# ------------------------------------------

Variable: 0